---
language: node_js
node_js:
  - "13"

dist: trusty

addons:
  chrome: stable

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

cache:
  yarn: true

jobs:
  fail_fast: true

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - yarn lint:js
        - yarn test

    - stage: "Additional Tests"
      name: 'Node 10'
      node_js: 10

    - name: 'Node 12'
      node_js: 12

    - name: 'Floating Dependencies'
      install: yarn install --no-lockfile --non-interactive --ignore-engines

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --ignore-engines

script:
  - yarn test

before_deploy:
  - yarn global add auto-dist-tag
  - auto-dist-tag --write

deploy:
  skip_cleanup: true
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: OVMYTMjIiSuBxCB0vQZJfaQzyeaR0U5dgRZaoc5CRd4yys9i+rL3PlJaWeeO6Lm950j+v6fDKHZg6aMLAhLOosZfkLEZh0ycvBSKq//ZI5yAhqnp9LV7/FGCEBT0ij1Mp3cqCaIlQIZjPo6lS+hIsYf3tqg1/cw2VOtDO4RprJ4=
  on:
    tags: true
    repo: babel/ember-cli-babel
