# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

cache:
  - '%APPDATA%\npm-cache'

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - md C:\nc
  - npm config set cache C:\nc
  - npm version
  - npm install phantomjs-prebuilt
  - npm install mocha-appveyor-reporter
  - npm install --no-optional

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
